- name : Configure Docker on EC2 Instances
  hosts : webserver
  become: true
  connection : ssh
  tasks : 
  - name: Deploying kubernetes pods
    command: kubectl create deployment insurancepod --image=docker.io/akhil2598/insurance:1.0 --port=8083
    command: kubectl expose deployment/insurancepod --port=8083 --target-port=8083 --type=NodePort
