- name : Configure Docker on EC2 Instances
  hosts : all
  become: true
  connection : ssh
  tasks : 
  - name: Deploying kubernetes pods
    command: kubectl create deployment insureme --image=docker.io/kondetimounika/insureme:1.0 --port=8081
    command: kubectl expose deployment/insureme --port=8081 --target-port=8081 --type=NodePort
